{
	"signature": "bfaaf18a1bcfd40335283ad538c8960793b8b39c6f4476eab73a8ecad5362aabdbbf657e7f8c63a94cb4825025befbb2191b7ae6577e24ad495b71175c87597d",
	"AltEndpoint": "false",
	"Credits": "Bakkes, Martinn, TaylorSasser, ButternCream, GlenHumphrey, Segal, ToolB0x, lchmagKekse, MrMythical, and Megasplat",
	"UninstallerUrl": "https://github.com/CodeRedModding/CodeRed-Launcher/releases/download/v2.5.9/CodeRedUninstaller.zip",
	"ModuleChangelog": "Added two new context menu options for the reflector window, you can now can copy an instances object index or its full name.\nAdded a new setting `thumbnail_load_delay` which lets you change the delay to wait for loading product assets.\nFixed textures exported as the `.jpg` format being partially corrupt due to the wrong color channels being written.\nFixed a rare crash that could happen after loading to the main menu then quickly entering the garage.\nFixed a crash with texture browser related to UTexture2D objects that had specific LOD Groups set.\nFixed `FScriptDelegate` property values not being read for classes instances in the reflector window.\nFixed ImGui windows not remembering if they were open from the last time you injected CodeRed.\nFixed the `freeplay_unlimited_flips` setting not applying to your dodge time as well.\nFixed custom color headlights not working on the main menu.\nMinor bug fixes and improvements to the thumbnail renderer.\nBackend changes to the internal API system.",
	"DropperUrl": "https://github.com/CodeRedModding/CodeRed-Launcher/releases/download/v2.5.9/CodeRedDropper.zip",
	"LauncherVersion": "1.4.2",
	"LauncherUrl": "https://github.com/CodeRedModding/CodeRed-Launcher/releases/download/v2.5.9/CodeRedLauncher.zip",
	"KofiUrl": "https://ko-fi.com/coderedmodding/",
	"LauncherAlt": "null",
	"DiscordUrl": "https://discord.gg/t4SjXjEhk3",
	"ModuleVersion": "2.5.9",
	"NewsUrl": "https://www.rocketleague.com/en/news/",
	"ModuleUrl": "https://github.com/CodeRedModding/CodeRed-Launcher/releases/download/v2.5.9/CodeRedModule.zip",
	"Supporters": "Synexe, MisterDrProf, Th3Ant, Anga, FREE AOL, Mr Reiner, Mirage, Redtracx, Lexi, Sierra, MrPhil, Reave",
	"Disclaimer": "CodeRed is not officially approved by Psyonix or Epic Games, however, CodeRed still follows Rocket League's ToU, EULA, and rules regarding third party modding. CodeRed does not provide a competitive advantage in online play, expose unreleased features/content, or abuse Rocket League's services.",
	"LauncherChangelog": "Added extra exception handling when injecting, and logging for said exception handling.\nChanged how news article dates are formatted in the news tab.",
	"PsyonixVersion": "250319.60456.478365",
	"WebsiteUrl": "https://coderedmodding.github.io/"
}