{
	"signature": "e1696b29929949a06a4db9331e4ce338dabedf46031bf599eb42d66f70371e530f38ee7fd5c429b75d42dca759c5df5a444566f47bf456c4d6fd947fe23b3813",
	"ModuleUrl": "https://github.com/CodeRedModding/CodeRed-Launcher/releases/download/v3.0.3/CodeRedModule.zip",
	"Disclaimer": "CodeRed is not officially approved by Psyonix or Epic Games, however, CodeRed still follows Rocket League's ToU, EULA, and rules regarding third party modding. CodeRed does not provide a competitive advantage in online play, expose unreleased features/content, or abuse Rocket League's services.",
	"LauncherUrl": "https://github.com/CodeRedModding/CodeRed-Launcher/releases/download/v3.0.3/CodeRedLauncher.zip",
	"WebsiteUrl": "https://coderedmodding.github.io/",
	"LauncherVersion": "1.4.6",
	"UninstallerUrl": "https://github.com/CodeRedModding/CodeRed-Launcher/releases/download/v3.0.3/CodeRedUninstaller.zip",
	"LauncherAlt": "null",
	"ModuleVersion": "3.0.3",
	"KofiUrl": "https://ko-fi.com/coderedmodding/",
	"AltEndpoint": "false",
	"Credits": "Bakkes, Martinn, TaylorSasser, ButternCream, GlenHumphrey, Segal, ToolB0x, lchmagKekse, MrMythical, Megasplat, and Stev",
	"NewsUrl": "https://www.rocketleague.com/en/news/",
	"ModuleChangelog": "The json key `ThemeName` for custom styles has been changed to `TerminalTheme`, custom styles will be updated with this new key upon injection.\nAdded a new setting `interface_disable_eac_popup`, which auto closes the Easy Anti-Cheat popup that appears after reaching the main menu.\nAdded four new flip timer settings in the offline tab, which lets you see how much time is left for your cars flip.\nFixed CodeRed not properly detecting you entering a workshop map, which made custom car colors not apply.\nDiscord rich presence will now show what workshop map you're in instead of saying `Unknown Map`.\nDiscord rich presence will now show map titles in the users language set in game, instead of only being in English.\nUpgraded the internal ImGui framework to version 1.92.8, which came with a new color for custom styles `CheckBoxSelectedBg`.",
	"PsyonixVersion": "260506.26700.517210",
	"LauncherChangelog": "Upgraded from `.NET 9.0` to `.NET 10.0`, which will require you to download the new runtime if you only have `.NET 9.0` installed.\nRewrote how dll injection is handled, it is much safer with more detailed error reporting, and it also now uses `LoadLibraryW` instead of `LoadLibraryA`.\nThe prevent injection if EAC is detected setting is now disabled by default for new users, injection will just fail gracefully if attempted to inject with EAC.\nRemoved the `Launch Rocket League` button to avoid confusion, as it required the user to manually put `-noeac` in their launch parameters.\nFixed the process status being stuck saying `East Anti-Cheat Detected` instead of saying if rocket league is running or not.\nIncreased the default injection time for new users from `2500` to `3500`.",
	"DotNetFramework": "10.0",
	"DropperUrl": "https://github.com/CodeRedModding/CodeRed-Launcher/releases/download/v3.0.3/CodeRedDropper.zip",
	"DiscordUrl": "https://discord.gg/FzEc7mFwjz",
	"Supporters": "Synexe, MisterDrProf, Th3Ant, AngaBlue, FREE AOL, MrReiner, Mirage, Redtracx, Emilybaddie, Aurabaddie, MrPhil, Pxscz, NiloXV, Jani, Techo, Munchkin, and Wheatmaize"
}