{
	"signature": "4595dbb56c690bf01eeb0d1e7250f2b40979efe6780123980fac1092a93334e5b731c7a9c5eeddb6be6b756aabe249eb0db04eb81e14697854d845e228a0d82b",
	"KofiUrl": "https://ko-fi.com/coderedmodding/",
	"LauncherVersion": "1.4.4",
	"Credits": "Bakkes, Martinn, TaylorSasser, ButternCream, GlenHumphrey, Segal, ToolB0x, lchmagKekse, MrMythical, and Megasplat",
	"WebsiteUrl": "https://coderedmodding.github.io/",
	"ModuleVersion": "2.7.1",
	"PsyonixVersion": "250610.60392.487806",
	"AltEndpoint": "false",
	"Supporters": "Synexe, MisterDrProf, Th3Ant, Anga, FREE AOL, Mr Reiner, Mirage, Redtracx, Lexi, Sierra, MrPhil, Reave, Nilo, Jani, Techo, and Madzoomies",
	"Disclaimer": "CodeRed is not officially approved by Psyonix or Epic Games, however, CodeRed still follows Rocket League's ToU, EULA, and rules regarding third party modding. CodeRed does not provide a competitive advantage in online play, expose unreleased features/content, or abuse Rocket League's services.",
	"ModuleUrl": "https://github.com/CodeRedModding/CodeRed-Launcher/releases/download/v2.7.1/CodeRedModule.zip",
	"ModuleChangelog": "Added five new settings that let you display the balls current speed under the offline tab.\nFixed the primary and accent color popups not working for loadout products in the dashboard.\nFixed some tooltip descriptions for certain settings being wrong in the dashboard.\nResized a lot of the text spacing and widget sizes in the dashboard to be more consistent.\nInternal stability improvements and safety measures related to custom textures.",
	"DropperUrl": "https://github.com/CodeRedModding/CodeRed-Launcher/releases/download/v2.7.1/CodeRedDropper.zip",
	"LauncherAlt": "null",
	"LauncherUrl": "https://github.com/CodeRedModding/CodeRed-Launcher/releases/download/v2.7.1/CodeRedLauncher.zip",
	"UninstallerUrl": "https://github.com/CodeRedModding/CodeRed-Launcher/releases/download/v2.7.1/CodeRedUninstaller.zip",
	"LauncherChangelog": "Added a custom caching system for web requests due to GitHubs new rate limits, this should fix possible issues with downloading version info.\nRemade the internal logging system to have a lot more detail.\nInternal code refactoring and memory optimizations.",
	"NewsUrl": "https://www.rocketleague.com/en/news/",
	"DiscordUrl": "https://discord.gg/t4SjXjEhk3"
}